// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOhy8GGITkNOXFM7FBMJ947nq2CoDSMWU',
    appId: '1:542661350780:web:117fb89912ddb3d1ea80f9',
    messagingSenderId: '542661350780',
    projectId: 'todoapplication-cfb16',
    authDomain: 'todoapplication-cfb16.firebaseapp.com',
    storageBucket: 'todoapplication-cfb16.firebasestorage.app',
    measurementId: 'G-5KLR8FYHHN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLWskTkNKVa-cyk3tTMyqvxkFb8VMPMkI',
    appId: '1:542661350780:android:6cde4ae5ad969327ea80f9',
    messagingSenderId: '542661350780',
    projectId: 'todoapplication-cfb16',
    storageBucket: 'todoapplication-cfb16.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvKKl4sMnYI4mBB9B58AXu-Lnwxd7QZzI',
    appId: '1:542661350780:ios:283922fb6e7b84d0ea80f9',
    messagingSenderId: '542661350780',
    projectId: 'todoapplication-cfb16',
    storageBucket: 'todoapplication-cfb16.firebasestorage.app',
    iosBundleId: 'com.example.appTodoApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvKKl4sMnYI4mBB9B58AXu-Lnwxd7QZzI',
    appId: '1:542661350780:ios:283922fb6e7b84d0ea80f9',
    messagingSenderId: '542661350780',
    projectId: 'todoapplication-cfb16',
    storageBucket: 'todoapplication-cfb16.firebasestorage.app',
    iosBundleId: 'com.example.appTodoApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOhy8GGITkNOXFM7FBMJ947nq2CoDSMWU',
    appId: '1:542661350780:web:7b8e985ec1d0079aea80f9',
    messagingSenderId: '542661350780',
    projectId: 'todoapplication-cfb16',
    authDomain: 'todoapplication-cfb16.firebaseapp.com',
    storageBucket: 'todoapplication-cfb16.firebasestorage.app',
    measurementId: 'G-BJV6FDT45C',
  );
}
